### PR TITLE
java11 module compatibility

### PR DESCRIPTION
**Pull request by Svenner80**
I have changed the path for the 64 bit executable so that it also works with Java 11 and modules.

### CODE REVIEW

**Comment by fracpete** [comment]
Thanks for the PR.

Could you please supply a minimal example demonstrating that the renaming works under Java 11, but not with the old naming convention?

Also, do you have any documentation that corroborates this renaming?

**Comment by Svenner80** [comment]
Hi, 
I have created a default JavaFX project with rsyn4j v3.2.3-5. When I compile it, I get the error message:

 [WARNING] There are 1 pathException(s). The related dependencies will be ignored.
 [WARNING] Dependency: C:\Users\augus\.m2\repository\com\github\fracpete\rsync4j-windows-x86_64\3.2.3-5\rsync4j-windows-x86_64-3.2.3-5.jar
   - exception: Unable to derive module descriptor for C:\Users\augus\.m2\repository\com\github\fracpete\rsync4j-windows-x86_64\3.2.3-5\rsync4j-windows-x86_64-3.2.3-5.jar
   - cause: rsync4j.windows.x86.64: Invalid module name: '64' is not a Java identifier
[WARNING] Can't extract module name from rsync4j-windows-x86_64-3.2.3-5.jar: rsync4j.windows.x86.64: Invalid module name: '64' is not a Java identifier

An example would be:
https://github.com/Svenner80/rsync4jModuleCompatibilityFX.git

**Comment by fracpete** [comment]
Thanks, that was very helpful. 

Personally, I don't use `module-info.java` at all, since most of projects predate Java 9 by a number of years (I started with Java 1.2). When compiling your project using Java 11, I only received a warning, but not the error that you reported (`openjdk version "11.0.11" 2021-04-20`).

Instead of renaming the artifacts and directories, etc, I opted for the simpler approach of adding the `Automatic-Module-Name` entry to the jar manifests, using valid Java identifers (these changes have been pushed out). At my end, this made the warning in your FX project disappear.

Please update the rsync4j code base, recompile/install rsync4j and then use `3.2.3-6-SNAPSHOT` as dependency version in your project.

Current mapping of artifacts to modules:
* `rsync4j-core` -> `rsync4j.core`
* `rsync4j-windows-x86` -> `rsync4j.windows32`
* `rsync4j-windows-x86_64` -> `rsync4j.windows64`
* `rsync4j-all` -> `rsync4j.all`

**Comment by Svenner80** [comment]
I don't use java modules either but it seems to be necessary here...

I also tried it with `Automatic-Module-Name` and it didn't work. Also with your solution I get the problem that the compiler does not accept it.

If you then call `Binaries.sshBinary();` once in the programme, you get the error message:

`java.lang.IllegalStateException: Failed to read list of libraries from: com/github/fracpete/rsync4j/windows-x86_64/libraries.txt`

**Comment by fracpete** [comment]
What version of java do you use?

**Comment by Svenner80** [comment]
adopt-openjdk-11.0.12
Maven 3.6.3

JavaFX 16

**Comment by fracpete** [comment]
Pretty much the same stack that I use. Will have a closer look at it again the next couple of days.

**Comment by fracpete** [comment]
OK, I've renamed modules and resource paths. Also left the `Automatic-Module-Name` for the jars.
Since I didn't get any warnings/errors when compiling or running the JavaFX app, I've pushed out a new release: 3.2.3-6

**Pull request closed without merging**
